export const SAVE_TEMP_ASSESSMENT = "SAVE_TEMP_ASSESSMENT";
export const ALTER_TEMP_ASSESSMENT_GRADE = "ALTER_TEMP_ASSESSMENT_GRADE";

export const SAVE_ASSESSMENT = "SAVE_ASSESSMENT";
export const ALTER_GRADE = "ALTER_GRADE";

export const SET_ACTIVE = "SET_ACTIVE";
