export const SAVE_RUBRIC = "SAVE_RUBRIC";
export const REMOVE_RUBRIC = "REMOVE_RUBRIC";

export const APPEND_BLOCK = "APPEND_BLOCK";
export const REMOVE_BLOCK = "REMOVE_BLOCK";

export const APPEND_CRITERION = "APPEND_CRITERION";
export const REMOVE_CRITERION = "REMOVE_CRITERION";

export const ALTER_CRITERION_TEXT = "ALTER_CRITERION_TEXT";
export const ALTER_CRITERION = "ALTER_CRITERION";

export const ALTER_BLOCK_TITLE = "ALTER_BLOCK_TITLE";

export const REORDER_CRITERION = "REORDER_CRITERION";
export const MOVE_CRITERION = "MOVE_CRITERION";

export const EDITING_RUBRIC = "EDITING_RUBRIC";

export const SAVE_RUBRIC_BACKUP = "SAVE_RUBRIC_BACKUP";