export const SET_SELECTED_ELEMENT = "SET_ELEMENT_OPENED";

export const SAVE_RUBRIC = "SAVE_RUBRIC";
export const SAVE_TEMP_RUBRIC = "SAVE_TEMP_RUBRIC";

export const DELETE_RUBRIC = "DELETE_RUBRIC";

export const EDITING_RUBRIC = "EDITING_RUBRIC";

export const PUSH_RUBRIC_PATH = "PUSH_RUBRIC_PATH";
export const POP_RUBRIC_PATH = "POP_RUBRIC_PATH";

export const ADD_BLOCK = "ADD_BLOCK";
export const ADD_CRITERION = "ADD_CRITERION";

export const DELETE_ELEMENT = "DELETE_ELEMENT";
export const DELETE_ALL_ELEMENTS = "DELETE_ALL_ELEMENTS";

export const ALTER_TITLE = "ALTER_TITLE";
export const ALTER_CRITERION_TEXT = "ALTER_CRITERION_TEXT";
export const ALTER_CRITERION_GRADE = "ALTER_CRITERION_GRADE";
